train:
  id: melee
  size: [72, 96] # y, x instead of x, y pixel dims? i think?
num_actions: 160 # 80 for each player
path_data_low_res: null # TO DEFINE
path_data_full_res: null # TO DEFINE
keymap: melee
