_target_: agent.AgentConfig

denoiser:
  _target_: models.diffusion.DenoiserConfig
  sigma_data: 0.5
  sigma_offset_noise: 0.1
  noise_previous_obs: true
  upsampling_factor: null
  inner_model:
    _target_: models.diffusion.InnerModelConfig
    img_channels: 3
    num_steps_conditioning: 4
    cond_channels: 256
    depths:
    - 2
    - 2
    - 2
    - 2
    channels:
    - 16
    - 32
    - 64
    - 128
    attn_depths:
    - 0
    - 0
    - 1
    - 1

upsampler: null  # Set to null to disable upsampling network
rew_end_model: null
actor_critic: null
